version: '3.7'
services:
  web:
    build: './build/'
    container_name: php_web_app
    ports:
    - "80:80"
    volumes:
    - /home/ubu/agrobrain:/var/www/html

  db:
    image: mysql:latest
    container_name: mysql_db
    ports:
    - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "datos_usuario"
    volumes:
    - ./mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyuadmin:5.1.1
    container_name: phpmyadmin_container
    ports:
    - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
